-- CREATE DATABASE coingecko_api_db IF NOT EXISTS; 

CREATE TABLE coins IF NOT EXISTS (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  coin_id VARCHAR(50) NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  platforms json DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

